# anomalize_timeseries { #wass2s.anomalize_timeseries }

```python
anomalize_timeseries(ds, clim_year_start=None, clim_year_end=None)
```

Compute anomalies by subtracting the climatological mean.

## Parameters {.doc-section .doc-section-parameters}

| Name            | Type                               | Description                                                              | Default    |
|-----------------|------------------------------------|--------------------------------------------------------------------------|------------|
| ds              | xarray.Dataset or xarray.DataArray | Input dataset or data array.                                             | _required_ |
| clim_year_start | int                                | Start year of the climatology period. If None, uses the full time range. | `None`     |
| clim_year_end   | int                                | End year of the climatology period. If None, uses the full time range.   | `None`     |

## Returns {.doc-section .doc-section-returns}

| Name   | Type                               | Description                                   |
|--------|------------------------------------|-----------------------------------------------|
|        | xarray.Dataset or xarray.DataArray | Anomalized dataset or data array (ds - mean). |

## Notes {.doc-section .doc-section-notes}

Anomalies are computed as ds - mean, where mean is calculated over the
specified climatology period or the entire time dimension.