# build_iridl_url_ersst { #wass2s.build_iridl_url_ersst }

```python
build_iridl_url_ersst(
    year_start,
    year_end,
    bbox,
    run_avg=3,
    month_start='Jan',
    month_end='Dec',
)
```

Build a parameterized IRIDL URL for NOAA ERSST dataset.

## Parameters {.doc-section .doc-section-parameters}

| Name        | Type   | Description                                                                                      | Default    |
|-------------|--------|--------------------------------------------------------------------------------------------------|------------|
| year_start  | int    | Start year for the data request.                                                                 | _required_ |
| year_end    | int    | End year for the data request.                                                                   | _required_ |
| bbox        | list   | Bounding box coordinates in the format [North, West, South, East].                               | _required_ |
| run_avg     | int    | Number of time steps for running average (default is 3). If None, no running average is applied. | `3`        |
| month_start | str    | Starting month for the time range (default is 'Jan').                                            | `'Jan'`    |
| month_end   | str    | Ending month for the time range (default is 'Dec').                                              | `'Dec'`    |

## Returns {.doc-section .doc-section-returns}

| Name   | Type   | Description                                          |
|--------|--------|------------------------------------------------------|
|        | str    | Constructed IRIDL URL for accessing NOAA ERSST data. |

## Notes {.doc-section .doc-section-notes}

The bounding box is reordered to match IRIDL's expected format: Y/(south)/(north)/, X/(west)/(east)/.