# load_gridded_predictor { #wass2s.load_gridded_predictor }

```python
load_gridded_predictor(
    dir_to_data,
    variables_list,
    year_start,
    year_end,
    season=None,
    model=False,
    month_of_initialization=None,
    lead_time=None,
    year_forecast=None,
)
```

Load gridded predictor data for reanalysis or model.

## Parameters {.doc-section .doc-section-parameters}

| Name                    | Type   | Description                                                                                       | Default    |
|-------------------------|--------|---------------------------------------------------------------------------------------------------|------------|
| dir_to_data             | str    | Directory path where predictor data is stored.                                                    | _required_ |
| variables_list          | str    | Variable string in the format 'center.variable'.                                                  | _required_ |
| year_start              | int    | Start year of the data.                                                                           | _required_ |
| year_end                | int    | End year of the data.                                                                             | _required_ |
| season                  | list   | List of month numbers defining the season.                                                        | `None`     |
| model                   | bool   | If True, load model data (hindcast/forecast); otherwise, load reanalysis data (default is False). | `False`    |
| month_of_initialization | int    | Month of model initialization (required if model=True).                                           | `None`     |
| lead_time               | list   | List of lead times in months (required if model=True).                                            | `None`     |
| year_forecast           | int    | Forecast year (required for forecast data if model=True).                                         | `None`     |

## Returns {.doc-section .doc-section-returns}

| Name   | Type             | Description                                         |
|--------|------------------|-----------------------------------------------------|
|        | xarray.DataArray | Loaded predictor data array renamed to 'predictor'. |

## Notes {.doc-section .doc-section-notes}

Converts dataset to data array, drops 'variable' dimension, and ensures datetime64[ns] time coordinates.