# process_model_for_other_params { #wass2s.process_model_for_other_params }

```python
process_model_for_other_params(
    agmParamModel,
    dir_to_save,
    hdcst_file_path,
    fcst_file_path,
    obs_hdcst,
    obs_fcst_year,
    month_of_initialization,
    year_start,
    year_end,
    year_forecast,
    nb_cores=2,
    agrometparam='Onset',
)
```

Process model hindcast and forecast data for agrometeorological parameters.

## Parameters {.doc-section .doc-section-parameters}

| Name                    | Type           | Description                                                                      | Default    |
|-------------------------|----------------|----------------------------------------------------------------------------------|------------|
| agmParamModel           | object         | Model object with a compute method for processing agrometeorological parameters. | _required_ |
| dir_to_save             | str            | Directory path to save processed data.                                           | _required_ |
| hdcst_file_path         | dict           | Dictionary mapping model names to hindcast file paths.                           | _required_ |
| fcst_file_path          | dict           | Dictionary mapping model names to forecast file paths.                           | _required_ |
| obs_hdcst               | xarray.Dataset | Observational hindcast dataset.                                                  | _required_ |
| obs_fcst_year           | xarray.Dataset | Observational forecast dataset for the specified year.                           | _required_ |
| month_of_initialization | int            | Month of model initialization.                                                   | _required_ |
| year_start              | int            | Start year of the hindcast data.                                                 | _required_ |
| year_end                | int            | End year of the hindcast data.                                                   | _required_ |
| year_forecast           | int            | Forecast year.                                                                   | _required_ |
| nb_cores                | int            | Number of CPU cores for parallel processing (default is 2).                      | `2`        |
| agrometparam            | str            | Name of the agrometeorological parameter (default is 'Onset').                   | `'Onset'`  |

## Returns {.doc-section .doc-section-returns}

| Name   | Type   | Description                                                                                                 |
|--------|--------|-------------------------------------------------------------------------------------------------------------|
|        | tuple  | Tuple of dictionaries (saved_hindcast_paths, saved_forecast_paths) mapping model names to saved file paths. |